### PR TITLE
upgrade typescript to latest version

### LINKED ISSUE #1155: TS Bindings: Upgrade Typescript to latest
Upgrade the packaged Typescript version to the latest.
https://www.npmjs.com/package/typescript?activeTab=versions

### PR DESCRIPTION
**Pull request by Benjtalkshow**
closes #1155 

### Upgrade TypeScript to Latest Version
- Upgraded TypeScript to the latest stable version and updated tsconfig.json as needed.
- Refactored code to resolve any type errors introduced by the upgrade.
- Ran test and manual tests to ensure stability.

### CODE REVIEW

**Comment by Benjtalkshow** [comment]
@willemneal can you check my PR?

**Review by willemneal — APPROVED** [review]
LGTM! I'll let @chadoh also approve since he is more familiar

**Comment by Benjtalkshow** [comment]
> LGTM! I'll let @chadoh also approve since he is more familiar

Alright

**Comment by Benjtalkshow** [comment]
@willemneal 
When are they going to merge this PR?

**Review by chadoh — APPROVED** [review]
Thanks! Looks good

**Comment by leighmcculloch** [comment]
@chadoh @willemneal Is this okay to be merged?

**Review by chadoh — APPROVED** [review]
Thank you!

**Pull request merged**
