### PR TITLE
Use clap's validator instead.

### PR DESCRIPTION
**Pull request by fnando**
### What

Use a clap validator to parse the alias argument.

```console
$ stellar contract deploy --wasm ./target/wasm32-unknown-unknown/release/hello_world.wasm --network standalone --source alice --alias '!foo' --global
error: alias must be 1-30 chars long, and have only letters, numbers, underscores and dashes
```

### Why

So we can use a built-in feature.

### Known limitations

N/A

### CODE REVIEW

**Review by willemneal — CHANGES_REQUESTED** [review]
Could we have a test to show the error works?

**Comment by fnando** [comment]
@willemneal can you point me to a test I can borrow?

**Comment by willemneal** [comment]
[cmd/crates/soroban-test/tests/it/config.rs](https://github.com/stellar/stellar-cli/pull/1406/files#diff-f7fce5dbe5b3bdfc63fd5f3e8661920acf93db26642360a14e3ced385d472c82)

**Review by willemneal — APPROVED** [review]
We can use the new type solution later. Best to have something now.

**Pull request merged**
