### PR TITLE
fix: remove unneeded print statement

### LINKED ISSUE #1539: events: outputs invalid JSON
### What version are you using?

`v21.3.0`

### What did you do?

Requested the output of events in JSON form:

```
$ stellar events --start-ledger 1000515 --output json
{
  "type": "diagnostic",
  "ledger": 1000515,
  "ledgerClosedAt": "2024-08-11T18:20:19Z",
  "id": "0004297179204177920-0000000000",
  "pagingToken": "0004297179204177920-0000000000",
  "contractId": "",
  "topic": [
    "AAAADwAAAAdmbl9jYWxsAA==",
    "AAAADQAAACBVkqNeeMWaJ6fGFVD0NhNxSTQdXVfI6TONZODy5H/xvg==",
    "AAAADwAAAAlzZXRfcHJpY2UAAAA="
  ],
  "value": "AAAAEAAAAAEAAAACAAAAEAAAAAEAAAAQAAAACgAAAAAAAAAAU7CiG+HJShAAAAAKAAAAAAAAAAADqvucLHjDIgAAAAoAAAAAAAAAAAAAWvzqKM15AAAACgAAAAAAAAAAAAAz7BHJ4iwAAAAKAAAAAAAAAAAANOdwTbnMWQAAAAoAAAAAAAAAAAAAWvKqC0vOAAAACgAAAAAAAAAAAAAfDiD/rEgAAAAKAAAAAAAAAAAAB4yGUE68jgAAAAoAAAAAAAAAAAABpOHhhG/JAAAACgAAAAAAAAAAAAAmGsNlXeQAAAAKAAAAAAAAAAAAA7ZGtuJERAAAAAoAAAAAAAAAAAAAWvHB1yXiAAAACgAAAAAAAAAAAAHKF+UGqFIAAAAKAAAAAAAAAAAAAAkcwiD1iQAAAAoAAAAAAAAAAAACLe/o7dfAAAAACgAAAAAAAAAAAABj8qDTiisAAAAFAAABkUKrLIA="
}
...
{
  "type": "diagnostic",
  "ledger": 1000515,
  "ledgerClosedAt": "2024-08-11T18:20:19Z",
  "id": "0004297179204177920-0000000009",
  "pagingToken": "0004297179204177920-0000000009",
  "contractId": "",
  "topic": [
    "AAAADwAAAAxjb3JlX21ldHJpY3M=",
    "AAAADwAAAA93cml0ZV9kYXRhX2J5dGUA"
  ],
  "value": "AAAABQAAAAAAAAs8"
}
Latest Ledger: 1005534
```

### What did you expect to see?

JSON.

### What did you see instead?

JSON, followed by text appended at the end. Both are outputted to stdout, meaning the output of the command cannot be used as is and piped to programs that accept JSON.

### PR DESCRIPTION
**Pull request by willemneal**
fixes #1539

~Also fixes the the json returned is not valid and would have to be edited by the consumer to convert to a JSON list of events.~

### CODE REVIEW

**Review by leighmcculloch — APPROVED** [review]

**Comment by leighmcculloch** [comment]
@willemneal There's an e2e test failure.

**Comment by willemneal** [comment]
@leighmcculloch @chadoh I fixed the e2e test here, but I forget how to update it here since it's not on the stellar repo: https://github.com/stellar/system-test/pull/103

**Comment by leighmcculloch** [comment]
> I forget how to update it here

There's nothing to update in this repo, just rerun the test after the fix is merged. This repo uses the master branch of the system-test repo.

I've merged https://github.com/stellar/system-test/pull/103 and rerun the failed build: 
- https://github.com/stellar/stellar-cli/actions/runs/10612677809/job/29418324099?pr=1554

**Comment by willemneal** [comment]
@leighmcculloch Just realized that the e2e tests didn't even expect valid json. Fixed that in this PR and here: https://github.com/stellar/system-test/pull/104

**Review by leighmcculloch — APPROVED** [review]

**Pull request merged**
